getwd()
setwd("/home/s201500601123456/tutorial/tutorial6")
getwd()
vot.data = read.csv("korean_vot.csv")
attach(vot.data)
income ~ education
V_S <- VOT ~ Series
V_C <- VOT ~ Cons
vot.data
plain <- subset(vot.data,Series=='plain')
aspirated <- subset(vot.data,Series=='aspirated')
tense <- subset(vot.data,Series=='tense')
mean(plain$VOT)
mean(aspirated$VOT)
mean(tense$VOT)
boxplot(V_S, data = vot.data)
boxplot(V_C, data = vot.data)
boxplot(VOT ~ Place, data = vot.data)
anova(lm(V_S, data = vot.data))
anova(lm(V_C, data = vot.data))
vot.data$Place = ifelse(vot.data$Cons=="b"|vot.data$Cons=="B"|vot.data$Cons=="p", "labial", ifelse(vot.data$Cons=="d"|vot.data$Cons=="D"|vot.data$Cons=="t", "alveolar", "velar"))
vot.data$Place = as.factor(vot.data$Place)
anova(lm(VOT~Place + Series, data = vot.data))
m =lm(VOT~Place + Series, data = vot.data)
summary(m)
v.plain = subset(vot.data, Series=="plain")
v.aspirated = subset(vot.data, Series=="aspirated")
summary(v.plain)
summary(v.aspirated)
t.test(v.plain$VOT, v.aspirated$VOT)
t.test(plain$VOT, tense$VOT)
